ARG STACTOOLS_VERSION=latest
FROM stacutils/stactools:${STACTOOLS_VERSION}-dev

WORKDIR /opt/stactools-worldclim

# For caching purposes, install dependencies but remove the actual package
COPY pyproject.toml requirements-dev.txt setup.cfg ./
COPY src/stactools/worldclim/__init__.py src/stactools/worldclim/
RUN pip install -r requirements-dev.txt \
    && pip install . \
    && rm -r /opt/conda/lib/python3.8/site-packages/stactools/worldclim

COPY . ./
RUN pip install -e .
